// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJN22plh4zA20J2dXJG7_te0nCTphqnIE',
    appId: '1:772173379670:web:d6c4ddf4f40da92208e3f7',
    messagingSenderId: '772173379670',
    projectId: 'couplecore-bae2e',
    authDomain: 'couplecore-bae2e.firebaseapp.com',
    storageBucket: 'couplecore-bae2e.firebasestorage.app',
    measurementId: 'G-PG8XV9W4VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeWtNxkB_29O7_L-J1C9FNLyl2b8iwiDs',
    appId: '1:772173379670:android:5e7735315812003c08e3f7',
    messagingSenderId: '772173379670',
    projectId: 'couplecore-bae2e',
    storageBucket: 'couplecore-bae2e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJN22plh4zA20J2dXJG7_te0nCTphqnIE',
    appId: '1:772173379670:web:423943c083c7760708e3f7',
    messagingSenderId: '772173379670',
    projectId: 'couplecore-bae2e',
    authDomain: 'couplecore-bae2e.firebaseapp.com',
    storageBucket: 'couplecore-bae2e.firebasestorage.app',
    measurementId: 'G-PBY2LX5BV3',
  );
}
